truncate SLATE_DATA_STG.APPLICATIONS_GRAD_SUBPLANS
;

import into SLATE_DATA_STG.APPLICATIONS_GRAD_SUBPLANS
  (
   APPLICATION_SLATE_GUID ,
   APPLICATION_SLATE_ID ,
   GRADUATE_MASTERS_ACADEMIC_INTEREST,
   GRADUATE_DOCTORATE_ACADEMIC_INTEREST,
   GR_ANTHROPOLOGY_SUBPLAN,
   GR_ANTHROPOLOGY_SUBPLAN_EXPORT,
   GR_CIVILENGINEERING_SUBPLAN,
   GR_CIVILENGINEERING_SUBPLAN_EXPORT,
   GR_COUNSELING_SUBPLAN,
   GR_COUNSELING_SUBPLAN_EXPORT,
   GR_CURRICULUM_MASTERS_SUBPLAN,
   GR_CURRICULUM_MASTERS_SUBPLAN_EXPORT,
   GR_ENGINEERING_AND_APPLIED_SCIENCES_PHD_SUBPLAN,
   GR_ENGINEERING_AND_APPLIED_SCIENCES_PHD_SUBPLAN_EXPORT,
   GR_LEADERSHIP_AND_EDUCATION_EQUITY_EDD_SUBPLAN,
   GR_LEADERSHIP_AND_EDUCATION_EQUITY_EDD_SUBPLAN_EXPORT,
   GR_EDUCATION_AND_HUMAND_DEVELOPMENT_MA_SUBPLAN,
   GR_EDUCATION_AND_HUMAND_DEVELOPMENT_MA_SUBPLAN_EXPORT,
   GR_EDUCATION_AND_HUMAND_DEVELOPMENT_PARTNER_COHORT_SUBPLAN,
   GR_EDUCATION_AND_HUMAND_DEVELOPMENT_PARTNER_COHORT_SUBPLAN_EXPORT,
   GR_EDUCATION_DEVELOPMENT_PHD_SUBPLAN,
   GR_EDUCATION_DEVELOPMENT_PHD_SUBPLAN_EXPORT,
   GR_ENVIRONMENTAL_SCIENCE_SUBPLAN,
   GR_ENVIRONMENTAL_SCIENCE_SUBPLAN_EXPORT,
   GR_FIINANCE_AND_RISK_MANAGEMENT_SUBPLAN,
   GR_FIINANCE_AND_RISK_MANAGEMENT_SUBPLAN_EXPORT,
   GR_HISTORY_SUBPLAN,
   GR_HISTORY_SUBPLAN_EXPORT,
   GR_HUMANITIES_SUBPLAN,
   GR_HUMANITIES_SUBPLAN_EXPORT,
   GR_INFORMATIONSYSTEMS_SUBPLAN,
   GR_INFORMATIONSYSTEMS_SUBPLAN_EXPORT,
   GR_INFORMATION_AND_LEARNING_SYSTEMS_SUBPLAN,
   GR_INFORMATION_AND_LEARNING_SYSTEMS_SUBPLAN_EXPORT,
   GR_MBA_HEALTH_ADMINISTRATION_SUBPLAN,
   GR_MBA_HEALTH_ADMINISTRATION_SUBPLAN_EXPORT,
   GR_MASTER_OF_ENGINEERING_CIVIL_SUBPLAN,
   GR_MASTER_OF_ENGINEERING_CIVIL_SUBPLAN_EXPORT,
   GR_POLITICAL_SCIENCE_SUBPLAN,
   GR_POLITICAL_SCIENCE_SUBPLAN_EXPORT,
   GR_SOCIAL_SCIENCES_SUBPLAN,
   GR_SOCIAL_SCIENCES_SUBPLAN_EXPORT
  )
  from jdbc at SLATE_SQL statement
  'select  * from XDW_APPLICATIONS_GRAD_SUBPLANS'

  ERRORS INTO SLATE_DATA_STG.ERROR_TABLE ('SLATE - XDW_APPLICATIONS_GRAD_SUBPLANS - '|| LEFT(CAST(current_timestamp as VARCHAR(100)),10)) REJECT LIMIT UNLIMITED
