truncate table SLATE_DATA_STG.PERSON
;


import into SLATE_DATA_STG.PERSON
  (
	PROSPECT_ID,
	CUSIS_EMPLID,
	IDM_USERNAME,
	SLATE_REF,
	NAME,
	PREFIX,
	PREFERRED,
	FIRST_NAME,
	MIDDLE_NAME,
	LAST_NAME,
	SUFFIX,
	ALIAS_NAME,
	BIRTH_DATE,
	SEX,
	HISPANIC,
	RACE,
	CITIZENSHIP_STATUS,
	PRIMARY_CITIZENSHIP,
	PERMANENT_RESIDENT,
	SECONDARY_CITIZENSHIP,
	CUSIS_FERPA_PRIVACY,
	DEVICE_PRIMARY_PHONE,
	DEVICE_MOBILE_PHONE,
	EMAIL,
	STATUS,
	CIT_GRAD_VISA_TYPE,
	CIT_VISA_TYPE,
  PERMANENT_STREET_1,
	PERMANENT_CITY,
  PERMANENT_STREET_2,
	PERMANENT_REGION,
  PERMANENT_POSTAL,
  PERMANENT_COUNTY,
	PERMANENT_COUNTRY,
	CREATED_DATE,
	UPDATED_DATE
  )
  from jdbc at SLATE_SQL statement
  'select  * from build.XDW_PERSON'

  ERRORS INTO SLATE_DATA_STG.ERROR_TABLE ('SLATE - XDW_PERSON - '|| LEFT(CAST(current_timestamp as VARCHAR(100)),10)) REJECT LIMIT UNLIMITED
