truncate SLATE_DATA_STG.APPLICATIONS
;

import into SLATE_DATA_STG.APPLICATIONS
  (
	APPLICATION_SLATE_GUID,
	APPLICATION_SLATE_ID,
	CUSIS_APP_NBR,
	PROSPECT_ID,
	CUSIS_EMPLID,
	IDM_USERNAME,
	APPLICATION_FEE_DUE,
	APP_CREATED,
	APP_UPDATED,
	APP_SUBMITTED,
	APPLICATION_STATUS,
	DECISION_RELEASED_NAME,
	DECISION_RELEASED_DATE,
	APPLICATION_ROUND,
	APPLICATION_ROUND_KEY,
	CUSIS_APP_MATRICULATED,
	RF_ADMIT_TYPE,
	CUSIS_ORIGINAL_ADMIT_TERM,
	AI_ADMIT_TERM,
	RES_INSTATE_TUITION_DESIRE_YN,
	RESIDENCY_STATUS,
	RES_WUE_OPT_IN_YN,
	CUSIS_RECRUITMENT_SCHOLARSHIP,
	CUSIS_UGRD_MAJOR_PLAN,
	CUSIS_UGRD_MAJOR_PLAN_EXPORT,
	CUSIS_UGRD_MAJOR_PLAN_EXPORT4,
	CUSIS_UGRD_MAJOR_PLAN_EXPORT5,
	GRADUATE_MASTERS_ACADEMIC_INTEREST,
	GRADUATE_MASTERS_ACADEMIC_INTEREST_EXPORT,
	GRADUATE_MASTERS_ACADEMIC_INTEREST_EXPORT2,
	GRADUATE_DOCTORATE_ACADEMIC_INTEREST,
	GRADUATE_DOCTORATE_ACADEMIC_INTEREST_EXPORT,
	GRADUATE_DOCTORATE_ACADEMIC_INTEREST_EXPORT2,
  MISSING_CHECKLIST_ITEMS,
  SUBMITTED_CHECKLIST_ITEMS
  )
  from jdbc at SLATE_SQL statement
  'select  * from build.XDW_APPLICATIONS'

  ERRORS INTO SLATE_DATA_STG.ERROR_TABLE ('SLATE - XDW_APPLICATIONS - '|| LEFT(CAST(current_timestamp as VARCHAR(100)),10)) REJECT LIMIT UNLIMITED
